apiVersion: v1
kind: Service
metadata:
  name: sps-test-service
spec:
  selector:
    app: spstest
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 8090
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sps-test
spec:
  selector:
    matchLabels:
      app: spstest
  replicas: 4
  template:
    metadata:
      labels:
        app: spstest
    spec:
      containers:
      - name: spstest
        image: spstest:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8090