"""se añadio la columna de imagenes a la tabla de pets

Revision ID: 288cca1baee5
Revises: e9a35cd8538a
Create Date: 2021-10-10 22:21:48.103346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '288cca1baee5'
down_revision = 'e9a35cd8538a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pet', sa.Column('image_s3_key', sa.String(length=75), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pet', 'image_s3_key')
    # ### end Alembic commands ###
