"""changes to pet table

Revision ID: e9a35cd8538a
Revises: 0b59889ee2d2
Create Date: 2021-10-10 13:40:28.531037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9a35cd8538a'
down_revision = '0b59889ee2d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('weight', sa.Float(precision=2), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('tipo_animal', sa.String(length=50), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['client_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('pets')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pets',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), nullable=False),
    sa.Column('weight', sa.FLOAT(), nullable=False),
    sa.Column('height', sa.INTEGER(), nullable=False),
    sa.Column('owner_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['client_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('pet')
    # ### end Alembic commands ###
